/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sidescrollergame;

import java.awt.Graphics;

/**
 *
 * @author Camiel
 */
public class StartMenu extends javax.swing.JFrame {

    /**
     * Creates new form StartMenu
     */
    
    static String difficulty;
    
    
    public StartMenu() {
        initComponents();
        warning.setVisible(false);
        System.out.println("init startmenu..");
    }
    
    public String getDifficulty() {
        return difficulty;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        StartButton = new javax.swing.JButton();
        easyBox = new javax.swing.JRadioButton();
        normalBox = new javax.swing.JRadioButton();
        hardBox = new javax.swing.JRadioButton();
        DifficultyLabel = new javax.swing.JLabel();
        warning = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Start menu");
        setPreferredSize(new java.awt.Dimension(1000, 500));
        setResizable(false);

        StartButton.setText("Play game!");
        StartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartButtonActionPerformed(evt);
            }
        });

        easyBox.setText("easy");
        easyBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                easyBoxActionPerformed(evt);
            }
        });

        normalBox.setText("normal");
        normalBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                normalBoxActionPerformed(evt);
            }
        });

        hardBox.setText("hard");
        hardBox.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                hardBoxStateChanged(evt);
            }
        });
        hardBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hardBoxActionPerformed(evt);
            }
        });

        DifficultyLabel.setText("Choose difficulty:");

        warning.setForeground(new java.awt.Color(255, 51, 51));
        warning.setText("Please select a difficulty level!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(408, 408, 408)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DifficultyLabel, javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(javax.swing.GroupLayout.Alignment.CENTER, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(hardBox)
                        .addComponent(normalBox)
                        .addComponent(easyBox))
                    .addComponent(StartButton, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(warning, javax.swing.GroupLayout.Alignment.CENTER))
                .addContainerGap(448, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(DifficultyLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(easyBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(normalBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hardBox)
                .addGap(26, 26, 26)
                .addComponent(warning)
                .addGap(31, 31, 31)
                .addComponent(StartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(128, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void normalBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_normalBoxActionPerformed
        // TODO add your handling code here:
        if (normalBox.isSelected()) {
            easyBox.setSelected(false);
            hardBox.setSelected(false);
        }
    }//GEN-LAST:event_normalBoxActionPerformed

    private void hardBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hardBoxActionPerformed
        // TODO add your handling code here:
        if (hardBox.isSelected()) {
            normalBox.setSelected(false);
            easyBox.setSelected(false);
        }
    }//GEN-LAST:event_hardBoxActionPerformed

    private void easyBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_easyBoxActionPerformed
        // TODO add your handling code here:
        if (easyBox.isSelected()) {
            normalBox.setSelected(false);
            hardBox.setSelected(false);
        }
    }//GEN-LAST:event_easyBoxActionPerformed

    private void StartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartButtonActionPerformed
        // TODO add your handling code here:
        if (easyBox.isSelected()) { difficulty = "easy"; }
        else if (normalBox.isSelected()) { difficulty = "normal"; }
        else if (hardBox.isSelected()) { difficulty = "hard"; }
        else {
            warning.setVisible(true);
        }
        
//        if (difficulty != null) { //start the game and pass along difficulty
//
//            //this.dispose();
//            this.setVisible(false);
//            
//        } 
    }//GEN-LAST:event_StartButtonActionPerformed

    
    private void hardBoxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_hardBoxStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_hardBoxStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartMenu().setVisible(true);
            }
        });
    }
    
    public void reset() {
        difficulty = null;
        //initComponents();
        //this.removeAll();
        this.revalidate();
        this.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DifficultyLabel;
    private javax.swing.JButton StartButton;
    private javax.swing.JRadioButton easyBox;
    private javax.swing.JRadioButton hardBox;
    private javax.swing.JRadioButton normalBox;
    private javax.swing.JLabel warning;
    // End of variables declaration//GEN-END:variables

}
